image: "node:12-alpine"

# variables:
#   YARN_CACHE_FOLDER: "/yarn"

before_script:
  - apk add yarn bash
  - yarn global add typescript
  - yarn cache dir
  - pwd

stages:
  - build
  - package

Build:Node:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
      - npm_modules/

Package:Binaries:
  stage: package
  script:
    - yarn global add pkg
    - yarn build-binaries
  artifacts:
    paths:
      - dist-binaries/
  dependencies:
    - Build:Node
