image: "node:12-alpine"

variables:
  YARN_CACHE_FOLDER: "${CI_PROJECT_DIR}/.cache/yarn"

cache:
  paths:
    - ".cache/yarn"
  key: "${CI_PROJECT_NAME}"
  policy: pull

before_script:
  - apk add yarn bash
  - yarn global add typescript
  - yarn cache dir
  - pwd

stages:
  - build
  - package

Build:Node:
  stage: build
  script:
    - apk add git
    - yarn build
  artifacts:
    paths:
      - dist/
      - node_modules/
  cache:
    untracked: true
    paths:
      - ".cache/yarn"
    key: "${CI_PROJECT_NAME}"
    policy: pull-push

Package:Binaries:
  stage: package
  script:
    - yarn global add pkg
    - yarn build-binaries
  artifacts:
    paths:
      - dist-binaries/
  dependencies:
    - Build:Node
